/** @type {import('tailwindcss').Config} */
const config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "Primary-50": "#e5f6fd",
        "Primary-White": "#ffffff",
        "Primary-500": "#00aeef",
        "Primary-700": "#185672",
        "Primary-800": "#0b2a39",
        "Secondary-500": "#028984",
        "Secondary-900": "#fdb933",
        "Text-Greyscale-500": "#9e9e9e",
        "Text-Greyscale-600": "#757575",
        "Text-Greyscale-700": "#616161",
        "Text-Greyscale-800": "#343434",
        "Text-General-Text-Light": "#212121",
        "Text-Buttons-White": "#ffffff",
        "Text-General-White": "#ffffff",
        "Text-General-Brand": "#0a86bb",
        "Surface-General-Surface-Greyscale-50": "#fafafa",
        "Surface-General-Surface-Greyscale-100": "#f5f5f5",
        "Surface-General-Surface-Greyscale-200": "#eeeeee",
        "Surface-General-Surface-General-White": "#ffffff",
        "Surface-General-Surface-General-Brand": "#00aeef",
        "Surface-General-Surface-Others-Green": "#00723b",
        "Surface-General-Surface-Others-Red": "#da2128",
        "Surface-General-Surface-Others-Blue": "#213f99",
        "Surface-General-Surface-Others-Purple": "#6c4099",
        "Surface-Others-Orange": "#ff981f",
        "Surface-Alerts-Success": "#06b217",
        "Surface-Background-Background-Green": "#f8fffc",
        "Surface-Background-Background-Blue": "#e8f4fd",
        "Surface-Background-Background-Orange": "#fff3f0",
        "Stroke-Greyscale-Greyscale-300": "#e0e0e0",
        "Stroke-Greyscale-Greyscale-200": "#eeeeee",
        "Stroke-Greyscale-Greyscale-800": "#353535",
        "Stroke-Colors-Border-Single-Stroke-Divider-Light": "#eeeeee",
        "Greyscale-300": "#e0e0e0",
        "Greyscale-600": "#757575",
        "Greyscale-700": "#404040",
        "Border-Natural-400": "#d9dbe9",
        Alerts: "#e6b120",
        "Others-Orange": "#ff981f",
        "Text-Additionals-Absolute-900": "#212121",
        "Text-Components-Text-Form-Default-500": "#9e9e9e",
        "Surface-Light-And-Dark-Light-4": "#eeeeee",
      },
      fontFamily: {
        Abar_Low: ["AbarLow", "sans-serif"],
        Abar_Mid: ["AbarMid", "sans-serif"],
        Abar_High: ["AbarHigh", "sans-serif"],
        Abar_Low_FaNum: ["AbarLowFaNum", "sans-serif"],
        Abar_Mid_FaNum: ["AbarMidFaNum", "sans-serif"],
        Abar_High_FaNum: ["AbarHighFaNum", "sans-serif"],
        Abar_Low_NoEn: ["AbarLowNoEn", "sans-serif"],
        Abar_Mid_NoEn: ["AbarMidNoEn", "sans-serif"],
        Abar_High_NoEn: ["AbarHighNoEn", "sans-serif"],
        Abar_NoEn: ["AbarNoEn", "sans-serif"],
        Abar_Family: ["AbarFamily", "sans-serif"],
        Abar_NoEn_FaNum: ["AbarNoEnFaNum", "sans-serif"],
        Abar_Family_FaNum: ["AbarFamilyFaNum", "sans-serif"],
      },
      screens: {
        mob: "360px",
        tab: "1070px",
        project: "1080px",
      },
    },
  },
  plugins: [require("daisyui")],
};

export default config;
